services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    volumes:
      - ./backend/media:/var/media
    ports:
      - "4000:4000" # API
      - "9999-10010:9999-10010"
      - "9999-10010:9999-10010/udp" # SRT
    networks:
      - frontend
      - backend
    depends_on:
      fov-db:
        condition: service_healthy

    environment:
      - PORT=4000
      - DB_HOST=fov-db
      - DB_PORT=5432
      - DB_USER=root
      - SRT_PORT=9999
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=fovwebdb
      - FFMPEG_PATH=/usr/local/bin/ffmpeg
      - MEDIA_ROOT=/var/media
      - SRT_URL=${SRT_URL}
      - API_HOSTNAME=${API_URL}
      - TWITCH_ID=${TWITCH_ID}
      - TWITCH_SECRET=${TWITCH_SECRET}

  frontend:
    build:
      context: ./fov-angular
      args:
        - API_URL=${API_URL}

    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    # volumes: #DEV ONLY
    #  - ./fov-angular:/app
    #  - /app/node_modules
    ports:
      - "4200:80"
    networks:
      - frontend

  fov-db:
    image: postgres:18
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - fov-db:/var/lib/postgresql
      - ./fovwebdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d fovwebdb"]
      interval: 10s
      timeout: 5s
      retries: 10

    environment:
      POSTGRES_DB: fovwebdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

volumes:
  fov-db:
