version: "3"

services:
    nginx:
        build: ./nginx
        ports:
            - 8080:8080
            - 80:80
            - 1935:1935
        network_mode: host
        restart: on-failure

    proto:
        build: ./proto
        ports:
            - 8080:8080
        network_mode: host
        restart: on-failure
